version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hotel_service_postgres
    environment:
      POSTGRES_DB: hotel_service
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_password
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped 